---
title: "Multiple Parameters"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{multiple_paramters}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  eval = FALSE,
  comment = "#>"
)
```

# Load Libraries

```{r setup, message=FALSE}
library(sententia)
library(dplyr)
library(tidyr)
library(ggplot2)
library(purrr)
library(tidyquant)
```

# Map over parameters

I now create a very simple function `f` with two parameters: (1) media source and (2) news topic. 

```{r}
f <- function(source_in, topic_in){
  
  msi_data <- sent_index(
    source = source_in,
    topic = topic_in,
    freq = "month",
    dict = "loughran",
    aggr = "sent_logit"
  )
  
  msi_data %>% 
    # filter(published_date > "2019-06-01") %>% 
    rename(`Logit Aggregation` = sent_log) %>% 
    mutate(published_date = as.Date(published_date)) %>% 
    pivot_longer(names_to = "sentiment_type", values_to = "values", -c(source:aggr_type)) %>% 
    filter(sentiment_type == "Logit Aggregation")
}
```

Using this function, I specify the parameter combination over which I want to `map`. 

```{r}
setup <- crossing(source_in = c("all", "news24", "businessday"), 
                     topic_in = c("global", "economy", "industry", "markets", "politics"))

out <- purrr::pmap_dfr(setup, f) 
```

If you want to plot the output, a simple `facet_wrap` helps to plot the combinations in one graph.

```{r, fig.width=12}
out %>% 
  ggplot(., aes(published_date, values, group = sentiment_type), color = 1) +
  geom_line(color = "#BC4744") +
  geom_ma(color = "#18417B", n = 3, linetype = "solid", ma_fun = EMA) +
  labs(title = "Media Sentiment BER: Economic Focus", 
       subtitle = "Loughran (sent logit)",
       y = "Index", 
       x = "Date", 
       caption = "3 month EMA (Blue); Monthly Index (Red)") + 
  scale_x_date() +
  facet_wrap(topic ~ source, scales = "free_y", nrow = 4) +
  theme_tq()
```

